# Generated by Django 4.2.4 on 2023-08-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
